/-
# AnchoredSelectionPipeline

Connects the anchored CRT lattice interface (`AnchoredCRTLattice.lean`)
to the cluster-cover / adaptive-selection pipeline

**⚠️ Route-exploration file — NOT on the critical path of `erdos_306`.**
This file is part of the rational-collision / CRT-lattice component,
which is sorry-free algebra/combinatorics but is **disconnected** from
the main theorem `erdos_306`. The top result of this component,
`ResidualPrimeShellCRT.residualPrimeShellBound_of_intervalBound`,
assumes the shell bound as a hypothesis.
(`AdaptiveClusterSelection.lean`).

Formalizes the finite combinatorial pipeline:

  anchored hit
  ⟹ membership in an anchored reciprocal cluster
  ⟹ good tuple  ∨  low-codegree cover  ∨  high-incidence ledger.

No asymptotics, no SBEE, no analytic number theory.
The final arithmetic estimate remains a parameter/hypothesis.
-/
import Mathlib
import RequestProject.AnchoredCRTLattice
import RequestProject.AdaptiveClusterSelection

open Finset
open Classical

noncomputable section

/-! ## Goal 1: Shortness predicate -/

-- We use `Short : ℤ → Prop` throughout.
-- The paper will later instantiate `Short x` as `0 < |x| ∧ |x| ≤ M`.

/-! ## Goal 2: Anchored cluster as a finite set -/

/-- The anchored cluster generated by parameters `(p, q0, x0)`:
    all `q ∈ F` such that there exist short `x, y` with `q * x - q0 * x0 = p * y`. -/
def anchoredCluster
    (Short : ℤ → Prop) (F : Finset ℤ)
    (p q0 x0 : ℤ) : Finset ℤ :=
  F.filter (fun q =>
    ∃ x y : ℤ, Short x ∧ Short y ∧ q * x - q0 * x0 = p * y)

/-- The family of all anchored clusters generated by finite parameter sets
    `P` (residual-prime candidates) and `X0` (reference short coordinates),
    with a fixed reference seed `q0`. -/
def anchoredClusterFamily
    (Short : ℤ → Prop) (F P X0 : Finset ℤ) (q0 : ℤ) :
    Finset (Finset ℤ) :=
  (P ×ˢ X0).image (fun px => anchoredCluster Short F px.1 q0 px.2)

/-! ## Goal 3: Anchored witness gives cluster membership -/

/-- An `AnchoredClusterWitness` places `q1` in the anchored cluster
    for parameters `(p, q0, x0)`. -/
theorem mem_anchoredCluster_of_witness_1
    (Short : ℤ → Prop) (F : Finset ℤ)
    (W : AnchoredClusterWitness)
    (hq1F : W.q1 ∈ F)
    (hx1 : Short W.x1)
    (hy1 : Short W.y1) :
    W.q1 ∈ anchoredCluster Short F W.p W.q0 W.x0 := by
  simp only [anchoredCluster, mem_filter]
  exact ⟨hq1F, W.x1, W.y1, hx1, hy1, W.h1⟩

/-- An `AnchoredClusterWitness` places `q2` in the anchored cluster. -/
theorem mem_anchoredCluster_of_witness_2
    (Short : ℤ → Prop) (F : Finset ℤ)
    (W : AnchoredClusterWitness)
    (hq2F : W.q2 ∈ F)
    (hx2 : Short W.x2)
    (hy2 : Short W.y2) :
    W.q2 ∈ anchoredCluster Short F W.p W.q0 W.x0 := by
  simp only [anchoredCluster, mem_filter]
  exact ⟨hq2F, W.x2, W.y2, hx2, hy2, W.h2⟩

/-- An `AnchoredClusterWitness` places `q3` in the anchored cluster. -/
theorem mem_anchoredCluster_of_witness_3
    (Short : ℤ → Prop) (F : Finset ℤ)
    (W : AnchoredClusterWitness)
    (hq3F : W.q3 ∈ F)
    (hx3 : Short W.x3)
    (hy3 : Short W.y3) :
    W.q3 ∈ anchoredCluster Short F W.p W.q0 W.x0 := by
  simp only [anchoredCluster, mem_filter]
  exact ⟨hq3F, W.x3, W.y3, hx3, hy3, W.h3⟩

/-- An `AnchoredClusterWitness` places `q4` in the anchored cluster. -/
theorem mem_anchoredCluster_of_witness_4
    (Short : ℤ → Prop) (F : Finset ℤ)
    (W : AnchoredClusterWitness)
    (hq4F : W.q4 ∈ F)
    (hx4 : Short W.x4)
    (hy4 : Short W.y4) :
    W.q4 ∈ anchoredCluster Short F W.p W.q0 W.x0 := by
  simp only [anchoredCluster, mem_filter]
  exact ⟨hq4F, W.x4, W.y4, hx4, hy4, W.h4⟩

/-! ## Goal 4: Bad tuple covered by one anchored cluster -/

/-- A finite set `S` of seed primes is covered by an anchored hit if there
    exist parameters `p ∈ P` and `x0 ∈ X0` such that `S` is contained in
    the anchored cluster `anchoredCluster Short F p q0 x0`. -/
def coveredByAnchoredHit
    (Short : ℤ → Prop) (F P X0 : Finset ℤ) (q0 : ℤ)
    (S : Finset ℤ) : Prop :=
  ∃ p ∈ P, ∃ x0 ∈ X0,
    S ⊆ anchoredCluster Short F p q0 x0

/-- If `S` is covered by an anchored hit, then it is covered by some cluster
    in the anchored cluster family. -/
theorem coveredBySomeCluster_of_coveredByAnchoredHit
    (Short : ℤ → Prop) (F P X0 : Finset ℤ) (q0 : ℤ)
    (S : Finset ℤ)
    (h : coveredByAnchoredHit Short F P X0 q0 S) :
    coveredBySomeCluster (anchoredClusterFamily Short F P X0 q0) S := by
  obtain ⟨p, hp, x0, hx0, hS⟩ := h
  exact ⟨anchoredCluster Short F p q0 x0,
    Finset.mem_image.mpr ⟨(p, x0), Finset.mem_product.mpr ⟨hp, hx0⟩, rfl⟩,
    hS⟩

/-- Conversely, if `S` is covered by some cluster in the family, then it is
    covered by an anchored hit. -/
theorem coveredByAnchoredHit_of_coveredBySomeCluster
    (Short : ℤ → Prop) (F P X0 : Finset ℤ) (q0 : ℤ)
    (S : Finset ℤ)
    (h : coveredBySomeCluster (anchoredClusterFamily Short F P X0 q0) S) :
    coveredByAnchoredHit Short F P X0 q0 S := by
  obtain ⟨C, hCmem, hSC⟩ := h
  simp only [anchoredClusterFamily, mem_image, mem_product] at hCmem
  obtain ⟨⟨p, x0⟩, ⟨hp, hx0⟩, rfl⟩ := hCmem
  exact ⟨p, hp, x0, hx0, hSC⟩

/-! ## Goal 5: Good tuple / all-covered dichotomy in anchored language -/

/-- There exists a `k`-element subset of `F` not covered by any anchored cluster. -/
def hasAnchoredGoodKSubset
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (k : ℕ) : Prop :=
  hasGoodKSubset (anchoredClusterFamily Short F P X0 q0) F k

/-- Every `k`-element subset of `F` is covered by some anchored cluster. -/
def allKSubsetsAnchoredCovered
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (k : ℕ) : Prop :=
  allKSubsetsCovered (anchoredClusterFamily Short F P X0 q0) F k

/-- Dichotomy: either a good k-subset exists, or all k-subsets are covered. -/
theorem anchored_good_or_allCovered
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (k : ℕ) :
    hasAnchoredGoodKSubset Short F P X0 q0 k
    ∨ allKSubsetsAnchoredCovered Short F P X0 q0 k :=
  good_or_allKSubsetsCovered (anchoredClusterFamily Short F P X0 q0) F k

/-! ## Goal 6: Low-codegree cover theorem in anchored language -/

/-- The anchored cluster codegree of `T`: number of anchored clusters containing `T`. -/
def anchoredClusterCodegree
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (T : Finset ℤ) : ℕ :=
  clusterCodegree (anchoredClusterFamily Short F P X0 q0) T

/-- Low-codegree cover bound in anchored language:
    if every k-subset is covered, `T ⊆ F`, `T.card + 1 = k`,
    the anchored codegree of `T` is at most `R`,
    and every anchored cluster containing `T` has size at most `L`,
    then `F.card ≤ T.card + R * L`. -/
theorem anchored_lowCodegree_card_bound
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (T : Finset ℤ) (k L R : ℕ)
    (hTsub : T ⊆ F)
    (hTcard : T.card + 1 = k)
    (hall : allKSubsetsAnchoredCovered Short F P X0 q0 k)
    (hR : anchoredClusterCodegree Short F P X0 q0 T ≤ R)
    (hL : ∀ C ∈ clustersContaining (anchoredClusterFamily Short F P X0 q0) T,
          C.card ≤ L) :
    F.card ≤ T.card + R * L :=
  allCovered_lowCodegree_gives_card_bound
    (anchoredClusterFamily Short F P X0 q0) F T k L R
    hTsub hTcard hall hR hL

/-! ## Goal 7: High-incidence ledger in anchored language -/

/-- The anchored subset-cluster incidence count. -/
def anchoredSubsetClusterIncidence
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (m : ℕ) : ℕ :=
  subsetClusterIncidence (anchoredClusterFamily Short F P X0 q0) F m

/-- Lower bound: if every `m`-subset of `F` has anchored codegree ≥ `R`,
    the total anchored incidence is large. -/
theorem anchored_incidence_lower_of_all_high_codegree
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (m R : ℕ)
    (hhigh : ∀ T, T ⊆ F → T.card = m →
      R ≤ anchoredClusterCodegree Short F P X0 q0 T) :
    (F.powerset.filter (fun T => T.card = m)).card * R
      ≤ anchoredSubsetClusterIncidence Short F P X0 q0 m :=
  incidence_lower_of_all_high_codegree
    (anchoredClusterFamily Short F P X0 q0) F m R hhigh

/-- Double-counting upper bound for anchored incidence. -/
theorem anchored_incidence_upper_bound
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (m : ℕ) :
    anchoredSubsetClusterIncidence Short F P X0 q0 m
      ≤ ∑ C ∈ anchoredClusterFamily Short F P X0 q0,
        ((F ∩ C).powerset.filter (fun T => T.card = m)).card :=
  incidence_upper_bound (anchoredClusterFamily Short F P X0 q0) F m

/-- If every anchored cluster intersects `F` in at most `L` points,
    the incidence is bounded by `|family| * C(L, m)`. -/
theorem anchored_incidence_le_clusters_mul_choose
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (m L : ℕ)
    (hL : ∀ C ∈ anchoredClusterFamily Short F P X0 q0,
          (F ∩ C).card ≤ L) :
    anchoredSubsetClusterIncidence Short F P X0 q0 m
      ≤ (anchoredClusterFamily Short F P X0 q0).card * Nat.choose L m :=
  incidence_le_clusters_mul_choose
    (anchoredClusterFamily Short F P X0 q0) F m L hL

/-! ## Goal 8: Conditional endpoint pipeline theorem -/

/-- The full finite anchored selection pipeline:
    Either
    (1) a good k-subset exists (uncovered by any anchored cluster), or
    (2) `F.card ≤ T.card + R * L` (low-codegree cover bound), or
    (3) `R < anchoredClusterCodegree` (high codegree, leading to
        high incidence).

    This packages the dichotomy and the two cases (low-codegree / high-codegree)
    into a single statement. -/
theorem anchored_selection_pipeline
    (Short : ℤ → Prop)
    (F P X0 : Finset ℤ) (q0 : ℤ) (T : Finset ℤ) (k L R : ℕ)
    (hTsub : T ⊆ F)
    (hTcard : T.card + 1 = k)
    (hL : ∀ C ∈ clustersContaining (anchoredClusterFamily Short F P X0 q0) T,
          C.card ≤ L) :
    hasAnchoredGoodKSubset Short F P X0 q0 k
    ∨ F.card ≤ T.card + R * L
    ∨ R < anchoredClusterCodegree Short F P X0 q0 T := by
  rcases anchored_good_or_allCovered Short F P X0 q0 k with hgood | hall
  · exact Or.inl hgood
  · by_cases hR : anchoredClusterCodegree Short F P X0 q0 T ≤ R
    · exact Or.inr (Or.inl (anchored_lowCodegree_card_bound
        Short F P X0 q0 T k L R hTsub hTcard hall hR hL))
    · push_neg at hR
      exact Or.inr (Or.inr hR)

end
