import RequestProject.R2SelectedQReady
import RequestProject.R2Weights

open Finset BigOperators GlobalControl

noncomputable section

namespace CircleMethod

/-!
# R2 weights from a mass-batch supply

A `R2MassBatchSupply D` already carries the residual reciprocal-load window.
This leaf turns that window into the canonical uniform `Weights D` package and
threads it through the selected-`Q` ready socket.
-/

namespace R2MassBatchSupply

variable {T : Finset ℕ} {b : ℕ} {D : R2ConcreteData T b}

/-- The canonical uniform weight package generated by the mass-batch load
window. -/
def weights (QB : R2MassBatchSupply D) (hb : 0 < b) :
    R2ConcreteData.Weights D :=
  let hwindow := D.total_recipLoad_window_of_residual
    QB.hloadDisj QB.hloadLower QB.hloadUpper
  R2ConcreteData.weights_of_recipLoad_window D hb hwindow.1 hwindow.2

end R2MassBatchSupply

/-- Final component/mass socket with the Bernoulli weights generated directly
from the mass-batch reciprocal-load window. -/
theorem exists_arcConstruction_of_componentScaleCardMassSupply_autoWeights
    {T : Finset ℕ} {b : ℕ}
    (hb : 3 ≤ b) (hbpos : 0 < b)
    (D : R2ConcreteData T b) (N : ℤ)
    (Bblock Bextra ρ K : ℝ)
    (hadm : admissibleGlobalRange D.BS)
    (hρle : ρ ≤ 1 / 10)
    (hK : K * 100000 * ρ ^ 3 ≤ 1 / 10)
    (hNL : 2 * N + 1 ≤ (D.L : ℤ))
    (S : R2ComponentScaleCardSupply D N ρ K)
    (QB : R2MassBatchSupply D)
    (hNscale :
      (1 : ℝ) / Real.sqrt (sigmaE2 D.E (QB.weights hbpos).theta) ≤ (N : ℝ))
    (MB : R2MinorSupportBudgetData D (QB.weights hbpos) N Bblock Bextra)
    (hextraLight : ∑ e ∈ D.E \ ctrlEdges D.BS, 1 / (e : ℝ) ^ 2
        ≤ 3 * (sigmaCtrl D.BS) ^ 2)
    (hminorCtrl :
      Bblock + Bextra <
        (0.8 * (Real.exp (-(Real.pi ^ 2 / 2)) / 2)) / sigmaCtrl D.BS) :
    Nonempty (ArcConstruction T b) := by
  exact exists_arcConstruction_of_componentScaleCardMassSupply hb D (QB.weights hbpos)
    N Bblock Bextra ρ K hadm hNscale hρle hK hNL S QB MB
    hextraLight hminorCtrl

/-- Selected-`Q` endpoint with weights generated from the selected mass-batch
load window. -/
theorem exists_arcConstruction_of_selectedQ_coreSupply_autoWeights
    {T : Finset ℕ} {b : ℕ}
    (hb : 3 ≤ b) (hbpos : 0 < b)
    (D : R2ConcreteData T b) (Q : Finset ℕ) (N : ℤ)
    (Bblock Bextra ρ K : ℝ)
    (hadm : admissibleGlobalRange D.BS)
    (hρle : ρ ≤ 1 / 10)
    (hK : K * 100000 * ρ ^ 3 ≤ 1 / 10)
    (hNL : 2 * N + 1 ≤ ((D.withQ Q).L : ℤ))
    (S : R2ComponentScaleCoreSupply D N ρ)
    (hcomponentCard :
      ((ctrlEdges D.BS).card + Q.card + (gadgetEdges D.R D.S).card : ℝ) ≤ K)
    (QB : R2MassBatchSupply (D.withQ Q))
    (hNscale :
      (1 : ℝ) / Real.sqrt (sigmaE2 (D.withQ Q).E (QB.weights hbpos).theta)
        ≤ (N : ℝ))
    (MB : R2MinorSupportBudgetData (D.withQ Q) (QB.weights hbpos) N Bblock Bextra)
    (hextraLight :
      ∑ e ∈ (D.withQ Q).E \ ctrlEdges (D.withQ Q).BS, 1 / (e : ℝ) ^ 2
        ≤ 3 * (sigmaCtrl (D.withQ Q).BS) ^ 2)
    (hminorCtrl :
      Bblock + Bextra <
        (0.8 * (Real.exp (-(Real.pi ^ 2 / 2)) / 2)) /
          sigmaCtrl (D.withQ Q).BS) :
    Nonempty (ArcConstruction T b) := by
  exact exists_arcConstruction_of_selectedQ_coreSupply hb D Q (QB.weights hbpos)
    N Bblock Bextra ρ K hadm hNscale hρle hK hNL S hcomponentCard QB MB
    hextraLight hminorCtrl

end CircleMethod

end
